# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  [push, pull_request, workflow_dispatch]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-attack:
    runs-on: ubuntu-latest
    container: openjdk
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: TestAttack Run a multi-line script
        run: |
          cd Projects/P3
          java -version
          javac -version 
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestAttack.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestAttack
  
  test-consume:
    runs-on: ubuntu-latest
    container: openjdk
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: TestAttack Run a multi-line script
        run: |
          cd Projects/P3
          java -version
          javac -version 
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestConsume.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestConsume
  
  test-eatCookie:
    runs-on: ubuntu-latest
    container: openjdk
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: TestAttack Run a multi-line script
        run: |
          cd Projects/P3
          java -version
          javac -version 
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestMapEatCookie.java
          java -Djava.awt.headless=true -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapEatCookie
